# Generated by Django 4.1.4 on 2023-01-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("atracoes", "0001_initial"),
        ("enderecos", "0001_initial"),
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descrição", models.TextField()),
                ("aprovado", models.BooleanField(default=False)),
                ("atraçoes", models.ManyToManyField(to="atracoes.atracao")),
                ("avaliacoes", models.ManyToManyField(to="avaliacoes.avaliacao")),
                ("comentarios", models.ManyToManyField(to="comentarios.comentario")),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enderecos.endereco",
                    ),
                ),
            ],
        ),
    ]
