# Generated by Django 4.1.4 on 2023-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_turisticos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="pontos_turisticos"
            ),
        ),
    ]
