# Generated by Django 4.1.4 on 2023-01-02 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_turisticos", "0003_remove_pontoturistico_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocIdentificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="pontoturistico",
            name="doc_identificacao",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pontos_turisticos.docidentificacao",
            ),
        ),
    ]
